Repository openthread/pyspinel, pull requests merged in 2018-09, with the labels that each got.

#43 [spinel-cli] enhance for virtual time
  spinel-cli.py
  spinel/stream.py
Labels: enhancement

#44 [spinel-cli] close simulated node elegantly
  .travis/script.sh
  spinel/stream.py
Labels: bug, enhancement

#45 [python] add support for python3
  .travis.yml
  spinel-cli.py
  spinel/codec.py
  spinel/hdlc.py
  spinel/stream.py
  spinel/util.py
Labels: enhancement

#46 Update child table encoding
  spinel/codec.py
Labels: enhancement

#47 [github] add issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#50 [hdlc] return None when FCS does not pass
  spinel/hdlc.py
Labels: bug

#51 Fix child table encoding introduced in 408945e
  spinel/codec.py
Labels: bug
