Repository openthread/pyspinel, pull requests merged in 2019-10, with the labels that each got.

#78 [sniffer] add exec permission to sniffer.py
  sniffer.py
Labels: enhancement

#76 [sniffer] quick fix for python3 support
  README.md
  SNIFFER.md
  sniffer.py
  spinel/pcap.py
Labels: bug, enhancement

#80 [logging] fix python issues with logging and use proper logger
  spinel-cli.py
  spinel/codec.py
  spinel/config.py
  spinel/hdlc.py
  spinel/stream.py
  spinel/tun.py
Labels: bug

#81 [spinel-cli] add direct and indirect TX retry command
  spinel-cli.py
  spinel/codec.py
  spinel/const.py
Labels: enhancement

#82 [spinel-cli] fix problem with bufferinfo command
  spinel-cli.py
Labels: bug
